# docker-compose.yml
services:
  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - .git/
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:Xx123456@db:5432/microshop
    depends_on:
      - db
    networks:
      - server_network
    # Монтируем исходный код backend внутрь контейнера поверх образа
    volumes:
      - ./backend:/app

  db:
    image: postgres:latest
    volumes:
        - postgres_data:/var/lib/postgresql/
    environment:
        - POSTGRES_URL=postgres
        - POSTGRES_PASSWORD=Xx123456
        - POSTGRES_DB=microshop
    networks:
      - server_network

  # НОВЫЙ СЕРВИС FRONTEND
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      # Монтируем исходный код frontend внутрь контейнера
      - ./frontend:/app
      # Не монтируем node_modules из хоста, он будет внутри контейнера
    ports:
      # Открываем порт vite для отладки, если нужно. Важно: vite должен слушать 0.0.0.0
      - "5173:5173"
    networks:
      - server_network
    # Возможность наблюдать за изменениями в исходниках и перезапускать контейнер или синхронизировать файлы
    # зависит от реализации в Dockerfile.dev (npm run dev -- --host уже там)
    develop:
      watch:
        - path: ./frontend
          action: sync
          target: /app
          ignore:
            - node_modules/
            - dist/
            - .git/


  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: ./nginx/Dockerfile # Этот файл копирует dev.conf как default.conf
    ports:
      - 8080:80
    volumes:
      # УБИРАЕМ монтирование dist, так как frontend обслуживается отдельным контейнером
      # - ./frontend/dist:/usr/share/nginx/html:ro
      # Монтируем dev.conf как default.conf, чтобы он использовался как основная конфигурация
      # Это переопределяет копирование из Dockerfile, если нужно использовать compose для dev.
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
      # Можно также смонтировать conf.d, если нужно часто менять конфиг
      # - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
      - frontend # Теперь зависит и от frontend
    networks:
      - server_network
    # Убираем watch для nginx, так как конфиг меняется редко в dev, и мы используем volume mount
    # develop:
    #   watch:
    #     - path: ./nginx/dev.conf
    #       action: rebuild
    #       target: /etc/nginx/conf.d/default.conf

networks:
  server_network:
    driver: bridge
volumes:
  postgres_data: