# Use a alpine Python image
FROM python:3.13-alpine

# Install poetry
RUN pip install poetry

# Set the working directory inside the container
WORKDIR /app

# Copy poetry files
COPY ./backend/pyproject.toml ./backend/poetry.lock* ./

# Install dependencies
RUN poetry install --no-root

# Copy the application code (this will be mounted in dev, but for completeness)
# COPY ./backend .

# Expose the port your FastAPI app listens on
EXPOSE 8000

# Command to run the application with reload for development
CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]