[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.13"
fastapi = "^0.115.6"
uvicorn = {extras = ["standard"], version = "^0.32.1"}
sqlalchemy = {extras = ["asyncio"], version = "^2.0.36"}
asyncpg = "^0.30.0"
alembic = "^1.16.5"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
# Удаляем fastapi-users, passlib, bcrypt
# fastapi-users = {extras = ["sqlalchemy"], version = "^14.0.1"}
# passlib = {extras = ["bcrypt"], version = "^1.7.4"}
# bcrypt = "3.2.0"
# Добавляем pwdlib с поддержкой argon2
pwdlib = {extras = ["argon2"], version = "^0.3.0"}
fastapi-users = {extras = ["sqlalchemy"], version = "^15.0.0"}
pydantic-settings = "^2.0.0"


[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
flake8 = "^7.1.1"
isort = "^5.13.2"
mypy = "^1.11.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
skip-string-normalization = true
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.nox
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | api_v1/users/schemas.py  # Исключаем этот файл из форматирования black
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3