"""Change hashed_password to String

Revision ID: 98031b9a7322
Revises: 99141265b903
Create Date: 2025-10-10 10:23:21.162538

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "98031b9a7322"
down_revision: Union[str, Sequence[str], None] = "99141265b903"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "hashed_password",
        existing_type=postgresql.BYTEA(),
        type_=sa.String(length=1024),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "hashed_password",
        existing_type=sa.String(length=1024),
        type_=postgresql.BYTEA(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
