"""Add hashed_email to profile

Revision ID: 8ed4c79db229
Revises: 5e332fc090fa
Create Date: 2025-10-06 15:40:17.091763

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ed4c79db229"
down_revision: Union[str, Sequence[str], None] = "5e332fc090fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profile", sa.Column("email", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profile", "email")
    # ### end Alembic commands ###
