"""Add hashed_password to user

Revision ID: 5e332fc090fa
Revises: 62dfe3e7b819
Create Date: 2025-10-05 20:23:24.476334

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e332fc090fa"
down_revision: Union[str, Sequence[str], None] = "62dfe3e7b819"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "hashed_password",
            sa.LargeBinary(),
            server_default="Xx123456",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###
