"""Add users api to user model

Revision ID: 06563a2a8e6e
Revises: 62dfe3e7b819
Create Date: 2025-10-07 13:24:52.901490

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "06563a2a8e6e"
down_revision: Union[str, Sequence[str], None] = "62dfe3e7b819"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "hashed_password", sa.LargeBinary(length=1024), nullable=False
        ),
    )
    op.add_column(
        "user", sa.Column("email", sa.String(length=320), nullable=False)
    )
    op.add_column("user", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column(
        "user", sa.Column("is_superuser", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "user", sa.Column("is_verified", sa.Boolean(), nullable=False)
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_column("user", "is_verified")
    op.drop_column("user", "is_superuser")
    op.drop_column("user", "is_active")
    op.drop_column("user", "email")
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###
