"""remove id from AccessToken

Revision ID: a94d55451b66
Revises: 98031b9a7322
Create Date: 2025-10-10 12:21:58.276686

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a94d55451b66"
down_revision: Union[str, Sequence[str], None] = "98031b9a7322"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accesstoken", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accesstoken",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
