"""Add active to user

Revision ID: 355aa789cba7
Revises: 8ed4c79db229
Create Date: 2025-10-06 16:08:29.187703

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "355aa789cba7"
down_revision: Union[str, Sequence[str], None] = "8ed4c79db229"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "is_active", sa.Boolean(), server_default="TRUE", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_active")
    # ### end Alembic commands ###
