"""Add field password to user

Revision ID: 88a0056ed8a8
Revises: d32229aaf6a1
Create Date: 2025-10-01 16:16:43.211325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88a0056ed8a8"
down_revision: Union[str, Sequence[str], None] = "d32229aaf6a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "password",
            sa.String(length=32),
            server_default="Xx123456",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password")
    # ### end Alembic commands ###
