FROM nginx:alpine

# Copy the custom dev nginx configuration
COPY ./nginx/dev.conf /etc/nginx/conf.d/default.conf

# Nginx will serve files from here, which will be mounted during development
# No need to copy frontend files here as they will be mounted via volume in compose

EXPOSE 80

# Nginx runs on foreground by default
CMD ["nginx", "-g", "daemon off;"]